api_version = "2025-10"
uid = "1fd3c212-c1eb-0b21-c940-807d9f3c1cf61d4f522b"

[[extensions]]
type = "ui_extension"
name = "Houseplant Hospital"
handle = "hh-pos-checkout"
description = "Load pending Houseplant Hospital check-ins into the POS cart"

[[extensions.targeting]]
target = "pos.home.tile.render"
module = "./src/Tile.jsx"

[[extensions.targeting]]
target = "pos.home.modal.render"
module = "./src/Modal.jsx"

[extensions.capabilities]
api_access = false
network_access = true
